# Generated by Django 5.0.6 on 2024-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/offre/'),
        ),
    ]
